name = "PortHamiltonianSystems"
uuid = "6ff9205f-2186-4c35-b9d7-b7843b877754"
authors = ["Jonas Nicodemus <jonas.nicodemus@icloud.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
QuadraticOutputSystems = "7e166fd4-1274-4fbf-8c8d-3f6046b124b3"

[compat]
julia = "1"
