name = "QuadraticOutputSystems"
uuid = "7e166fd4-1274-4fbf-8c8d-3f6046b124b3"
authors = ["Jonas Nicodemus <jonas.nicodemus@icloud.com> and contributors"]
version = "1.0.0-DEV"

[deps]
ControlSystems = "a6e380b2-a6ca-5380-bf3e-84a91bcd477e"
ControlSystemsBase = "aaaaaaaa-a6ca-5380-bf3e-84a91bcd477e"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MatrixEquations = "99c1a7ee-ab34-5fd5-8076-27c950a045f4"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
ControlSystemsBase = "1.14.5"
Test = "1.11.0"
julia = "1"
